### ISSUE TITLE
Viewport Purge Error

### ISSUE THREAD

**Issue by TRTools** [ParallaxTeam/sharpRevit#1]
Taking into consideration that this is still WIP, this is what shows up when clicking on "Viewport Purge" tool

![image](https://github.com/ParallaxTeam/sharpRevit/assets/50882655/71792b3d-ba8d-4eaf-a0b4-b324025f3aa5)

**Comment by johnpierson** [comment]
Whoops. lol If you copy this DLL to the program directory it will work: https://github.com/ParallaxTeam/sharpRevit/blob/main/src/packages/CommunityToolkit.Mvvm.8.2.0/lib/net6.0/CommunityToolkit.Mvvm.dll

**Comment by johnpierson** [comment]
Give this installer a try for now. I will embed that code for the next release though:
https://github.com/ParallaxTeam/sharpRevit/releases/tag/1.0.2

**Comment by TRTools** [comment]
Great, it works great, thank you.
